/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "cluster_constants.h"

namespace ClusterEngine {

const clusterConstants g_cluster_constants;

clusterConstants::clusterConstants() {
}

} // namespace

