/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef cluster_CONSTANTS_H
#define cluster_CONSTANTS_H

#include "cluster_types.h"

namespace ClusterEngine {

class clusterConstants {
 public:
  clusterConstants();

};

extern const clusterConstants g_cluster_constants;

} // namespace

#endif
